### ISSUE TITLE
Doesn't work with non-latin caracters

### ISSUE THREAD

**Issue by katagen** [sigdeletras/project-reports-qgis-plugin#1]
If the layers containes non-latin caracters, like éàè and so on, it turns them into Ã© and others caracters.

**Comment by sigdeletras** [comment]
Hello

The data is generated in UTF-8 and the data is created with special characters (ñ, á, è...) are created without problem (my data is for example in Spanish).

Perhaps it is more an aspect of the program with which the files are opened that it should use the correct encoding system.

![image](https://user-images.githubusercontent.com/4746157/211900131-6b81aa78-d757-4e15-a5a9-6acf8756b32f.png)
