### ISSUE TITLE
[Feature request] Adding info about existing joins between layers

### ISSUE THREAD

**Issue by skampus** [sigdeletras/project-reports-qgis-plugin#3]
First of all, thank you very much for your work, it's very useful!

I wanted to ask if you think it would be possible to add indications of any existing joins between layers to the report 

thank you and ciao!

stefano campus

**Comment by sigdeletras** [comment]
Hi @skampus! 

Thanks for your words. I find it a good improvement for the plugin.

I'll look for information in the PyQGIS documentation. Surely there must be a class for extracting information from the relationships between layers. They may be in the QgsRelationManager class.

All the best

**Comment by sigdeletras** [comment]
Hi @skampus 

In version 1.2, pending approval, the following improvements have been included:

- Added a section on project relationships.
- Added an option to get the joints of the layers

Seeing the documentaction (README file) to more information.
