### ISSUE TITLE
Adding project metadata, CRS information

### ISSUE THREAD

**Issue by sdnxgr** [sigdeletras/project-reports-qgis-plugin#4]
Beautiful plugin - thank you for providing!
Would it be possible in a future version to include project metadata and CRS information?
Thanks!

**Comment by sigdeletras** [comment]
Thanks for the interest @sdnxgr 

The plugin already gets the CRS for the project and for each layer.

About metadata, what metadata do you think is relevant? And another question, do we usually fill in the metadata?

**Comment by sdnxgr** [comment]
I see that the CRS as ESPG number is provided already but I was imagining a more verbose display such as WGS84 / UTM Zone **N for example along with the ESPG number. Would benefit report recipients who are perhaps not  familiar with just the number.

I'm required to fill in metadata for my work, Was thinking that the Identification, Categories, and Contact tabs would be most useful as a "Metadata" object option in your main plugin widget.
Thanks again!

**Comment by sdnxgr** [comment]
To clarify the CRS question, I mean just adding the ESPG description for the project at the top, not for each layer.

**Comment by sigdeletras** [comment]
The information about the CRS is already included both in the project and in each of the layers. It is very common to work with layers in different CRSs and having this information is important.

**Comment by sigdeletras** [comment]
In version 1.2, **pending approval**, the following improvements have been included:

- Improved CRS information by adding its description next to the EPSG code
- Added summary field of the metadata section. The rest of the metadata could be added in another section. It will have to be analyzed.

**Comment by sdnxgr** [comment]
> The information about the CRS is already included both in the project and in each of the layers. It is very common to work with layers in different CRSs and having this information is important.

What I meant was if it takes up too much space, it might not be necessary to add the FULL CRS info for each layer, just the EPSG code, but to have the full info for the project at least.
You have provided both so thank you! Works great.
